name: Node-CI

on:
  push:
    branches:
      - master
      - develop
      

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[update]')"

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Environment preparation
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          chmod -R go= ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY }}" >> ~/.ssh/id_rsa

      - name: Install npm dependencies
        run: npm install

      - name: Run build task
        run: npm run build

  deploy-develop:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: [build]

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v2

      - name: Environment preparation
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          chmod -R go= ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY }}" >> ~/.ssh/id_rsa
          sudo apt-add-repository -y -u ppa:ansible/ansible
          sudo apt-get install -y rsync
          sudo apt-get install -y ansible 

      - name: Deploy to Server
        run: |
          chmod 700 ci-scripts
          cd ci-scripts
          ansible-playbook -i "${{ secrets.REMOTE_HOST }}" -e "ansible_user=${{ secrets.REMOTE_USER }} \ 
            INFURA=${{ secrets.INFURA_TESTNET }} \
            SERVER_HOST=${{ secrets.SERVER_HOST }} \
            ADDRESS_FACTORY=${{ secrets.ADDRESS_FACTORY }} \
            NUXT_PORT=${{ secrets.NUXT_PORT }}
            WEBSITE_PROCCESS=${{ secret.WEBSITE_PROCCESS_TESTNET }} 
            IS_MAINNET=${{ secrets.IS_MAINNET }} \
            SRC_DIR=${{ github.workspace }}/" website-update.yml;
            API_URL=${{ secrets.API_URL }} \
       
#
#  deploy-develop-bsc:
#
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/develop-bsc'
#
#    steps:
#      - name: Copy code files to container
#        uses: actions/checkout@v2
#
#      - name: Install Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'
#
#      - name: Install npm dependencies
#        run: npm install
#
#      - name: Run generate task
#        run: npm run generate
#        env:
#          INFURA: ${{ secrets.INFURA_TESTNET }}
#          NETWORK_ID: ${{ secrets.NETWORK_ID_TESTNET }}
#          FUNDRAISE_ADDRESS: ${{ secrets.FUNDRAISE_ADDRESS_TESTNET }}
#          FORMATIC_KEY: ${{ secrets.FORMATIC_KEY_TESTNET }}
#          PORTIS_ID: ${{ secrets.PORTIS_ID }}
#
#      - name: Deploy to Server
#        uses: easingthemes/ssh-deploy@v2.1.1
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#          ARGS: "-rltgoDzvO --delete"
#          SOURCE: "dist/"
#          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#          REMOTE_USER: ${{ secrets.REMOTE_USER }}
#          TARGET: ${{ secrets.REMOTE_TARGET }}
#
#  